app/models.py
from flask_login import UserMixin

from app.helpers.users import get_user_by_key

class UserData:
    def __init__(self, email, password) -> None:
        self.email = email
        self.password = password

class UserSignUp(UserData):
    def __init__(self, email, password, first_name, last_name, id_number, age, gender) -> None:
        super().__init__(email, password)
        self.first_name = first_name
        self.last_name = last_name
        self.id_number = id_number
        self.age = age
        self.gender = gender

class UserModel(UserMixin):
    def __init__(self, user_data: UserData) -> None:
        self.id = user_data.email
        self.password = user_data.password

    @staticmethod
    def query(email):
        user_doc = get_user_by_key(email)
        user_data = UserData(
            email=user_doc["email"],
            password=user_doc["password"]
        )

        return UserModel(user_data)

app/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, PasswordField, SubmitField, EmailField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length

class LoginForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Send')

class CreateUser(LoginForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last name', validators=[DataRequired()])
    id_number = IntegerField('Id number', validators=[DataRequired()])
    age = IntegerField('Age', validators=[DataRequired()])
    gender = SelectField('Gender', choices=['Male', 'Female', 'Other'], validators=[DataRequired()])
    submit = SubmitField('Send')

class SuccessStory(FlaskForm):
    score = SelectField(
        'Satisfaction level', 
        choices=['Good', 'Medium', 'Bad'], 
        validators=[DataRequired()]
    )
    story = StringField(
        "Success story", 
        validators=[DataRequired(), Length(min=10, max=250)]
    )
    recommendation = SelectField(
        'Do you recommend the platform?', 
        choices=['Yes', 'No'], 
        validators=[DataRequired()]
    )
    submit = SubmitField('Send')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager

from .config import Config
from .auth import auth
from .users import users
from .stories import stories
from .models import UserModel

login_manager = LoginManager()
login_manager.login_view = 'auth.login'

@login_manager.user_loader
def load_user(username):
    return UserModel.query(username)

def create_app():
    app = Flask(__name__)

    bootstrap = Bootstrap(app)

    app.config.from_object(Config)

    login_manager.init_app(app)

    app.register_blueprint(auth)
    app.register_blueprint(users)
    app.register_blueprint(stories)

    return app

app/stories/__init__.py
from flask import Blueprint

stories = Blueprint('stories', __name__, url_prefix='/stories')

from . import views

app/stories/views.py
from flask import render_template, flash
from flask_login import login_required, current_user

from app.forms import SuccessStory
from app.helpers.stories import create_story
from app.helpers.users import get_user_by_key

from . import stories

@stories.route('success_stories', methods=["GET", "POST"])
@login_required
def success_stories():
    success_story_form = SuccessStory()

    context = {
        'success_story_form': success_story_form
    }

    if success_story_form.validate_on_submit():
        email = current_user.id

        user_data = get_user_by_key(email)

        story_data = {
            "email": email,
            "first_name": user_data["first_name"],
            "last_name": user_data["last_name"],
            "age": user_data["age"],
            "score": success_story_form.score.data, 
            "story": success_story_form.story.data, 
            "recommendation": success_story_form.recommendation.data 
        }

        create_story(story_data)

        flash("Story sended")

    return render_template("success.html", **context)

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__, url_prefix='/users')

from . import views

app/users/views.py
from werkzeug.security import generate_password_hash 

from flask import render_template, flash, redirect, url_for
from flask_login import login_user

from app.models import UserSignUp, UserData, UserModel
from app.forms import CreateUser
from app.helpers.users import get_user_by_key, create_user

from . import users

@users.route('/signup', methods=['GET', 'POST'])
def signup():
    signup_form = CreateUser()

    context = {
        'signup_form': CreateUser()
    }

    if signup_form.validate_on_submit():
        email = signup_form.email.data
        password = signup_form.password.data
        
        user_doc = get_user_by_key(email)

        if not user_doc:
            email = signup_form.email.data
            password_hash = generate_password_hash(password)
            first_name = signup_form.first_name.data
            last_name = signup_form.last_name.data
            id_number = signup_form.id_number.data
            age = signup_form.age.data
            gender = signup_form.gender.data

            new_user = UserSignUp(
                email, 
                password_hash, 
                first_name, 
                last_name,
                id_number,
                age,
                gender
            )

            create_user(new_user)
 
            user = UserModel(UserData(email, password_hash))
            login_user(user)

            return redirect(url_for('home'))
        else:
            flash("The user already exist!")
    
    return render_template('signup.html', **context)

app/templates/Pages/Home/Index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My psycologist</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header class="header">
        <h1 class="title">My psycologist</h1>
        <nav>
            <ul class="main-nav">
                <li class="main-nav__item">Psychologist</li>
                <li class="main-nav__item">Sing in</li>
                <li class="main-nav__item">Sing up</li>

            </ul>
        </nav>
    </header>

    <main>
        <div class="search-bar">
            <input list="services" class="search-bar-input">
            <datalist id="services">
                <option value="Emotional Suport"></option>
                <option value="General"></option>
                <option value="Familiar"></option>
                <option value="Infantile"></option>

            </datalist> 

        </div>
       <div class="title-main-container">
        <h2 class="title-main">
            Success stories           
           </h2>
       </div>
       <section class="profesional-section">
            <figure>
                <img 
                    src="../../Resources/Images/Foto_psicologo.png" 
                    alt="Hombre">
            </figure>
            <div class="profesional-section2">
                
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, saepe. Aspernatur autem ullam officiis ut soluta ex neque, ipsam atque illum delectus corporis nobis adipisci, facilis, rerum quia recusandae repudiandae!

                </p>
            </div>
        </section>
        <section class="profesional-section">
            <figure>
                <img 
                    src="../../Resources/Images/Foto_mujer.png" 
                    alt="Hombre">
            </figure>
            <div class="profesional-section2">
                
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, saepe. Aspernatur autem ullam officiis ut soluta ex neque, ipsam atque illum delectus corporis nobis adipisci, facilis, rerum quia recusandae repudiandae!

                </p>
            </div>
        </section>
    
    </main>

</body>
</html>

app/templates/Pages/Home/Login/Index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My psycologist</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <form class="form" id="login">
            <h1 class="form__tittle">login</h1>
            <div class="form__message form__message--error"></div>
            <div class="form__input-group">
                <input type="text" class="form__input"autofocus placeholder="Username or email">
                <div class="form__input-error-message">This is an error message</div>
           </div>     
           <div class="form__input-group">
                <input type="password" class="form__input form__error--"autofocus placeholder="password">
                <div class="form__input-error-message"></div>
      </div>  
      <button class="form__button" type="submit">Continue</button>
      <p class="form__text">
            <a href="#" class="form__link">Forgot your pasword?</a>
      </p>
      <p class="form__text">
            <a class= "form__link" href="./" id="linkCreateAccount">Don't have account? Create account</a>
      </p>    
        </form>
    </div>
    <script src="./main.js"></script>
</body>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block head %}
    {{ super() }}
    <title>
        {% block title %}My psychologist | {% endblock %}
    </title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

{% endblock %}

{% block body %}
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}

    {% for message in get_flashed_messages() %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" 
                class="close" 
                data-dismiss="alert">
                &times;
            </button>
            {{ message }}
        </div>
    {% endfor %}

    {% block content %}{% endblock %}

    {% block scripts %}
        {{ super() }}
    {% endblock%}

{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% import 'macros.html' as macros%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
    {{ super() }}
    Home
{% endblock %}

{% block content %}
    {% if username %}
        <h1>Welcome {{ username | capitalize}} </h1>
    {% endif %}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macros%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
    {{ super() }}
    Home
{% endblock %}

{% block content %}
    {% if username %}
        <h1>Welcome {{ username | capitalize}} </h1>
    {% endif %}

    <ul class="list-group">
        {% for story in stories %}
            {{ macros.render_stories(story) }}
        {% endfor %}
    </ul>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}
    {{ super() }}
    Login
{% endblock %}

{% block content %}
    <div class="container">
        {{ wtf.quick_form(login_form) }}
    </div>
{% endblock %}

app/templates/macros.html
{% import 'bootstrap/wtf.html' as wtf %}

{% macro render_stories(story) %}
    <li class="list-group-item">
        <span class="badge">
            {{ story["first_name"] }}
            {{ story["last_name"] }}
            <br> <br>
            age: {{ story["age"] }}
        </span>

        
        <h4>Story</h4>
        {{ story["story"] }}

        <br><br>
        How did you feel using the platform? 
        <br>
        {{ story["score"] }}

        <br><br>
        Do you recommend the platform? 
        <br>
        {{ story["recommendation"] }}
    </li>
{% endmacro %}

{% macro render_movies(movie) %}
    <li class="list-group-item">
        <span class="badge">
            {{ movie["vote_average"] }}
        </span>
        {{ movie["title"] }}
    </li>
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button"
                class="navbar-toggle"
                data-toggle="collapse"
                data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{{ url_for('index') }}">
                <h4>My psychologist</h4>
            </a>

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('home') }}">Home</a></li>


                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    <li><a href="{{ url_for('stories.success_stories') }}">Tell your story</a></li>
                {% endif %}

                {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    <li><a href="{{ url_for('users.signup') }}">Signup</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

app/templates/signup.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
    {{ super() }}
    Signup
{% endblock %}

{% block content %}
    <div class="container">
        {{ wtf.quick_form(signup_form) }}
    </div>
{% endblock %}

app/templates/sing_up.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
    {{ super() }}
    Login
{% endblock %}

{% block content %}
    <div class="container">
        {{ wtf.quick_form(create_user) }}
    </div>
{% endblock %}

app/templates/success.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}
    {{ super() }}
    Success Story
{% endblock %}

{% block content %}
    <div>
        <h1>Tell us your story</h1>
    </div>

    <div class="container">
        {{ wtf.quick_form(success_story_form) }}
    </div>
{% endblock %}